# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\biblia.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(271, 312)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(100000, 100000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src\\ic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.directory_line = QtWidgets.QLineEdit(self.centralwidget)
        self.directory_line.setEnabled(False)
        self.directory_line.setDragEnabled(False)
        self.directory_line.setReadOnly(False)
        self.directory_line.setObjectName("directory_line")
        self.gridLayout_2.addWidget(self.directory_line, 1, 0, 1, 1)
        self.choose_file = QtWidgets.QPushButton(self.centralwidget)
        self.choose_file.setObjectName("choose_file")
        self.gridLayout_2.addWidget(self.choose_file, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.link_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.link_1.setObjectName("link_1")
        self.gridLayout_2.addWidget(self.link_1, 3, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.link_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.link_2.setObjectName("link_2")
        self.gridLayout_2.addWidget(self.link_2, 5, 0, 1, 2)
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setObjectName("start")
        self.gridLayout_2.addWidget(self.start, 10, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 6, 0, 1, 1)
        self.link_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.link_3.setObjectName("link_3")
        self.gridLayout_2.addWidget(self.link_3, 7, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 8, 0, 1, 1)
        self.herz_line = QtWidgets.QSpinBox(self.centralwidget)
        self.herz_line.setMinimum(1)
        self.herz_line.setObjectName("herz_line")
        self.gridLayout_2.addWidget(self.herz_line, 9, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 271, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "torch"))
        self.label_3.setText(_translate("MainWindow", "Директория с книгами"))
        self.choose_file.setText(_translate("MainWindow", "Выбрать файл"))
        self.label_2.setText(_translate("MainWindow", "Ссылка в html формате"))
        self.label_4.setText(_translate("MainWindow", "Ссылка в html формате"))
        self.start.setText(_translate("MainWindow", "Начать"))
        self.label_5.setText(_translate("MainWindow", "Ссылка в html формате"))
        self.label.setText(_translate("MainWindow", "Количество ссылок на странице"))
