# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\biblia.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(415, 434)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(415, 434))
        MainWindow.setMaximumSize(QtCore.QSize(415, 434))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(310, 350, 91, 31))
        self.start.setObjectName("start")
        self.directory_line = QtWidgets.QLineEdit(self.centralwidget)
        self.directory_line.setEnabled(False)
        self.directory_line.setGeometry(QtCore.QRect(20, 60, 271, 20))
        self.directory_line.setDragEnabled(False)
        self.directory_line.setReadOnly(False)
        self.directory_line.setObjectName("directory_line")
        self.herz_line = QtWidgets.QSpinBox(self.centralwidget)
        self.herz_line.setGeometry(QtCore.QRect(20, 300, 161, 22))
        self.herz_line.setMinimum(1)
        self.herz_line.setObjectName("herz_line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 280, 181, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 271, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 271, 16))
        self.label_3.setObjectName("label_3")
        self.choose_file = QtWidgets.QPushButton(self.centralwidget)
        self.choose_file.setGeometry(QtCore.QRect(310, 60, 91, 23))
        self.choose_file.setObjectName("choose_file")
        self.link_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.link_1.setGeometry(QtCore.QRect(20, 130, 271, 20))
        self.link_1.setObjectName("link_1")
        self.link_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.link_2.setGeometry(QtCore.QRect(20, 180, 271, 20))
        self.link_2.setObjectName("link_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 271, 16))
        self.label_4.setObjectName("label_4")
        self.link_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.link_3.setGeometry(QtCore.QRect(20, 230, 271, 20))
        self.link_3.setObjectName("link_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 271, 16))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 415, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "torch"))
        self.start.setText(_translate("MainWindow", "Начать"))
        self.label.setText(_translate("MainWindow", "Количество ссылок на странице"))
        self.label_2.setText(_translate("MainWindow", "Ссылка в html формате"))
        self.label_3.setText(_translate("MainWindow", "Директория с книгами"))
        self.choose_file.setText(_translate("MainWindow", "Выбрать файл"))
        self.label_4.setText(_translate("MainWindow", "Ссылка в html формате"))
        self.label_5.setText(_translate("MainWindow", "Ссылка в html формате"))
